# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Seshagy < Formula
  desc "Agent-aware terminal dashboard for tmux and herdr"
  homepage "https://github.com/lmilojevicc/seshagy"
  version "0.7.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lmilojevicc/seshagy/releases/download/v0.7.1/seshagy_0.7.1_darwin_amd64.tar.gz"
      sha256 "7272c92c9744a8d424f5a5190019f6a4bed46730ffda505ac62c1ed766945751"

      define_method(:install) do
        bin.install "seshagy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lmilojevicc/seshagy/releases/download/v0.7.1/seshagy_0.7.1_darwin_arm64.tar.gz"
      sha256 "71fbb0e3cfbb63c21dea6f6bfe13ac0b19d8fab06f68779edbc0a27b7d7b2718"

      define_method(:install) do
        bin.install "seshagy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lmilojevicc/seshagy/releases/download/v0.7.1/seshagy_0.7.1_linux_amd64.tar.gz"
      sha256 "7090ec27eb421a9c0f5944ffa39ad73a3e9bb970d5bacd5e7ba3afab7201a9cd"
      define_method(:install) do
        bin.install "seshagy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lmilojevicc/seshagy/releases/download/v0.7.1/seshagy_0.7.1_linux_arm64.tar.gz"
      sha256 "324e3945d7e71fcf99a3152067f33052f750917beaaa7cce71bb0873a5591812"
      define_method(:install) do
        bin.install "seshagy"
      end
    end
  end

  def caveats
    <<~EOS
      Built-in --ephemeral focus-loss dismissal replaces the former launcher.
      Wire a one-key launcher with: seshagy keybind install tmux (or: herdr)
      Requires tmux or herdr on PATH.
    EOS
  end
end
